const RIDE_TYPES = Object.freeze(['TRANSPORT', 'DELIVERY']);
const DELIVERY_CATEGORIES = Object.freeze(['FOOD', 'WATER', 'PARCEL']);
const RIDE_STATUSES = Object.freeze([
  'REQUESTED',
  'ACCEPTED',
  'ARRIVED',
  'STARTED',
  'COMPLETED',
  'CANCELLED',
]);
const RIDER_AVAILABILITY = Object.freeze([
  'AVAILABLE',
  'UNAVAILABLE',
  'BUSY',
]);
const PAYMENT_STATUSES = Object.freeze(['PENDING', 'PAID']);
const CANCELLATION_REQUEST_STATUSES = Object.freeze([
  'PENDING',
  'CONFIRMED',
  'RESUMED',
  'AUTO_CANCELLED',
]);
const CANCELLATION_MODES = Object.freeze([
  'IMMEDIATE',
  'MUTUAL',
  'AUTO_TIMEOUT',
]);
const CHAT_ACCESS_REQUEST_STATUSES = Object.freeze([
  'PENDING',
  'APPROVED',
  'REJECTED',
  'EXPIRED',
]);

const NEXT_RIDE_STATUS = Object.freeze({
  ACCEPTED: 'ARRIVED',
  ARRIVED: 'STARTED',
  STARTED: 'COMPLETED',
});

const CANCELLABLE_RIDE_STATUSES = Object.freeze(['REQUESTED', 'ACCEPTED']);

module.exports = {
  RIDE_TYPES,
  DELIVERY_CATEGORIES,
  RIDE_STATUSES,
  RIDER_AVAILABILITY,
  PAYMENT_STATUSES,
  CANCELLATION_REQUEST_STATUSES,
  CANCELLATION_MODES,
  CHAT_ACCESS_REQUEST_STATUSES,
  NEXT_RIDE_STATUS,
  CANCELLABLE_RIDE_STATUSES,
};
